from typing import Union, List
from openai import OpenAI

class OpenAIChat:
    """
    Loads and generates text using an OpenAI client.
        
    Attributes
    ----------
    model : str
        Name of model that will be used.
    client : OpenAI
        OpenAI client that is initialized.
        
    Parameters
    ----------
    model : str
        Name of model that will be used.
    api_key : str, optional (default=None)
        OpenAI API key. If None, raises error.

    Raises
    ------
    RuntimeError
        If no API key is provided.
    """
    def __init__(
        self, 
        model: str,
        api_key: str = None
    ):
        if api_key is None:
            raise RuntimeError("OPENAI_API_KEY is not set.")
        if not api_key:
            raise RuntimeError("OPENAI_API_KEY is not set.")
        
        self.client = OpenAI(api_key=api_key)
        self.model = model

    def generate_text(
        self,
        prompt: Union[List[str], str],
        max_tokens: int = 100,
        top_p: float = 0.95,
        temperature: float = 0.8
    ) -> str:
        """
        Uses the OpenAI client to generate text dependent on the prompt.
        
        Parameters
        ----------
        prompt : Union[list[str], str]
            Can be a list of prompts or a single prompt.
        max_tokens : int, optional(default=60)
            Total amount of tokens that will be used in the text generation.
        top_p : float, optional (default=0.95)
            Keeps the smallest set of tokens whose cumulative probability >= N.
        temperature : float, optional (default=0.8)
            Denotes the fraction of temperature that will be used when sampling.
            Lower T -> more deterministic.
            Higher T -> more random.

        Returns
        -------
        str
            Text generated by the model.
        """
        resp = self.client.chat.completions.create(
            model=self.model,
            messages=[{"role": "user", "content": prompt}],
            temperature=temperature,
            top_p=top_p,
            max_tokens=max_tokens,
        )
        return resp.choices[0].message.content